### ISSUE TITLE
[Refactor] Rename `scriptured-prayer-components` folder `frontend`

### ISSUE THREAD

**Issue by kenancasey** [PrayTeam/scriptured-prayer#68]
I propose renaming the `scriptured-prayer-components` folder `frontend`. I find the `scriptured-prayer-components` name confusing; I was especially confused when I showed it to the class of students. 

While we're discussing this, I'm also tempted to rename the `prayerapp` folder `backend` to be parallel with `frontend`. 

Please let me know what your thoughts are. @asherlloyd @Soyokaze-42

**Comment by Soyokaze-42** [comment]
I would prefer we have a working frontend before we rename anything else.

Also, the frontend is split between those two directories since Django and React are coupled by the Django templating engine. There is not a whole lot of frontend in the prayerapp directory, but it is important.

**Comment by kenancasey** [comment]
I consider all the Django templating stuff the backend. What do you consider the frontend that's in the prayerapp folder?

**Comment by Soyokaze-42** [comment]
I look at html/css/javascript as all part of the frontend. We have a decent amount of that coming out of the admin and DRF modules that we are using. Of the bits we have created in prayerapp, index.html gets rendered by the Django templating engine (the backend) which includes all the react components from the SPA which then gets rendered by the user's browser (the frontend).

**Comment by asherlloyd** [comment]
Yes, I see merit in both viewpoints here. The `prayerapp` naming is due to the folder being a Django app (created via `manage.py`) as listed under the `INSTALLED_APPS` section. I understand that convention can be a little confusing, so I wanted to clarify that. I hesitate to name it backend for the reasons already listed above, being that Django is neither backend nor frontend exclusively but a mixture. I could see it being renamed to `prayer_app` to match `scriptured_prayer` but I'll let @Soyokaze-42 decide on that. I think renaming `scriptured-prayer-components` -> `frontend` would be fine.

**Comment by asherlloyd** [comment]
Closing as completed.
